### ISSUE TITLE
Cannot get this library to recognise the source/dest as equal

### ISSUE THREAD

**Issue by Xymanek** [AutoMapper/AutoMapper.Collection#108]
Here are the relevant parts of my code:
```csharp
    public class VotablePosition
    {
        [Key] public int Id { get; set; }
        // ....
    }

    public class CouncilRoleForm
    {
        // null means new
        public int? Id { get; set; }
        // ....
    }

// Mapper config:
cfg.AddCollectionMappers();
cfg.CreateMap<VotablePosition, CouncilRoleForm>()
    .EqualityComparison((position, form) => position.Id == form.Id)
    .ForMember(form => form.Name, op => op.MapFrom(position => position.HumanName))
    
    .ReverseMap()
    .EqualityComparison((form, position) => form.Id == position.Id)
    .ForMember(position => position.Id, op => op.Ignore()); // Do not touch the ID
```

However when an instance of `List<CouncilRoleForm>` is mapped to an instance of `ICollection<VotablePosition>` (with same contents) all of destination's members are removed and new ones are created :( 
Using JetBrains Rider's debugger/decompiler I tracked the problem to following part:

https://github.com/AutoMapper/AutoMapper.Collection/blob/58f73f9b793fe8f75313c00d37baffbc00a9e82c/src/AutoMapper.Collection/Mappers/EquivalentExpressionAddRemoveCollectionMapper.cs#L30-L34

https://github.com/AutoMapper/AutoMapper.Collection/blob/58f73f9b793fe8f75313c00d37baffbc00a9e82c/src/AutoMapper.Collection/EquivalencyExpression/EquivalentExpression.cs#L78-L85

The `sourceHash` is always 0 (from `return _destinationHashCodeFunc(obj as TDestination);`), meaning `TryGetValue` always fails (the actual IDs are non-null, non-0 values), however my C# knowledge is not enough to debug how that expression/delegate get built.

I've tried making the DTO property non-nullable, this didn't change the result

Package versions:
```xml
  <package id="AutoMapper" version="7.0.1" targetFramework="net45" />
  <package id="AutoMapper.Collection" version="4.0.0" targetFramework="net45" />
```

**Comment by Tasteful** [comment]
@Xymanek Can you make a [gist](https://help.github.com/articles/creating-gists/) that reproduces the problem for us? or add how the mappings are done. 

From what I read is that you map an `List<CouncilRoleForm>` (source) directly to an list of `ICollection<VotablePosition>` (destination), to get the collection mapper to work I think you need to have the source and destination collections as property on the main entity that you map.

**Comment by Xymanek** [comment]
The mappings are done inside `HttpApplication.Application_Start` using the static approach (`Mapper.Initialize(cfg =>`). Do you want me to (try) make a failing test case?

Both collections are properties on respective sides - `ICollection<VotablePosition> Positions` in entity (destination and non-null at time of mapping) and `List<CouncilRoleForm> Roles` in form/dto (source). Except for the collection problem (this issue) AutoMapper works perfectly fine in all other aspects

**Comment by Tasteful** [comment]
It also exists an version on the myget feed that have an updated comparison check to handle null properties.

You can find that version here https://myget.org/feed/automapperdev/package/nuget/AutoMapper.Collection

**Comment by Xymanek** [comment]
It turns out that the problem was a mistake on my end - this library perfectly handles nullable ints (the normal nuget version, didn't try the dev feed) and the mapping is kept same as I posted above. I apologize for wasting everybody's time and I'll post an explanation later in case somebody has same problem later (on mobile now)

**Comment by Xymanek** [comment]
Ok so here is what happened: I'm using `TryUpdateModel` (ASP.NET MVC) to patch an existing object with values submitted by user. Since the number/order of `CouncilRoleForm` cannot be changed by user, I didn't include the `Id` inside the user input. However, turns out that `TryUpdateModel` completely rebuilds the `List<CouncilRoleForm> Roles` (which sets `Id`s to `0`). As such, this library was properly trying to map back to `VotablePosition` with `Id` of `0`. I dunno how I missed this at first...
