### ISSUE TITLE
Mapping of collection element not done

### ISSUE THREAD

**Issue by athanorsprl** [AutoMapper/AutoMapper.Collection#110]
Hi,

I'm new with AutoMapper and AutoMapper.Collection and I have problem mapping collection property from our ORM object to DTO object.  We are working with a custom ORM and code is in VBnet.

We have this kind of ORM objects:

```
Class Device
Public Property Name As String
Public Property DeviceTypes As KernelCollection
End Class

Class DeviceType
Public Property Name As String
EndClass

```
`KernelCollection` class implement the `IList` interface.

We have the corresponding DTO objects:

```
Class DeviceDto
Plublic Property Name As String
Public Property DeviceTypes As List(Of DeviceType)
End Class

Class DeviceTypeDto
Public Property Name As String
End Class
```

Mapping of `Device` to `DeviceDto` is working correctly even with device types presents, `Device` in converted to `DeviceDto` and the types collection is correcly filled with `DeviceTypeDto` instances.

Mapping of `DeviceDto` to `Device` is working if I ignore device types property.

When I try to map a `DeviceDto` to `Device` with types the AutoMapper add an instance of the `DeviceTypeDto` type instead of a `DeviceType` (ORM object) to the `KernelCollection` instance of the `Device` object.

AutoMapper is configured like this:

```
Dim config As New AutoMapper.Configuration.MapperConfigurationExpression

config.AddCollectionMappers

config.CreateMap(Of DeviceType, DeviceTypeDto)
config.CreateMap(Of DeviceTypeDto, DeviceType)().EqualityComparison(Function(src1, dest1) src1.Name.Equals(dest1.Name))

config.CreateMap(Of DeviceFamily, DeviceFamilyDto)()
config.CreateMap(Of DeviceFamilyDto, DeviceFamily)().EqualityComparison(Function(src1, dest1) src1.Name.Equals(dest1.Name))

AutoMapper.Mapper.Initialize(config)
```

Any iead of the problem?  Is it because I'm using a custom collection at the ORM side?

Thanks!

**Comment by athanorsprl** [comment]
You are right!  The KernelCollection implements `IList` and not `IList(Of ...)`.

Ok, I understand... In this case only one mapping exists from `DeviceTypeDto`, is there any way of telling AutoMapper to use this default mapping?

**Comment by TylerCarlson1** [comment]
Make KernelCollection implement `IList(Of DeviceTypeDto)` would be the default way to get it to work.
Or use `ForMember` and explicitly map it out yourself mapping it to an array and pass it into the KernelCollection.

**Comment by athanorsprl** [comment]
Ok, I will get a try!  Thanks :)
