### ISSUE TITLE
Which version for Framework 4

### ISSUE THREAD

**Issue by athanorsprl** [AutoMapper/AutoMapper.Collection#113]
Hi,

Is there a version compatible with Framework 4?  I'm using AutoMapper version 6.2.2 which is the last version compatible with Framework 4.

Thanks,

Bruno.

**Comment by jbogard** [comment]
You know 4.0 was end of life’d i’m January 2016, right?

**Comment by athanorsprl** [comment]
I know... but some production environments are still in Windows 2003... Industrial company does not necessary like to change something that runs!

**Comment by TylerCarlson1** [comment]
They are all 4.5 back way before 6.2.2.  You would have to take the solution and compile with .NET 4.0 if you wanted a version with it.
