### ISSUE TITLE
Feature: Persistence methods return mapped objects

### ISSUE THREAD

**Issue by milkyware** [AutoMapper/AutoMapper.Collection#119]
Hi,

Currently the persistence operations are voids meaning that, particularly for inserts, its difficult to see what the mapped object is as the creation in the dbset is all done for you and don't even know what the created Id is. If the InsertOrUpdate method returned it would make presenting what the final inserted/updated object looked like.

Thanks

**Comment by TylerCarlson1** [comment]
You would have to call SaveChanges first before the ID would be generated.

I think it would make a EF proxy object and be updated after save changes if you were to return it.

A PR is always welcome.
