### ISSUE TITLE
Add/Edit but not Delete

### ISSUE THREAD

**Issue by evanjehl** [AutoMapper/AutoMapper.Collection#123]
Is it possible to override the behavior of EqualityComparison so that items in the destination collection are not deleted if they don't meet the comparison? In other words, the mapper would add records from the source collection that don't exist in the destination collection and edit matching records in the destination collection, but not delete any records in the destination collection. I am thinking about a scenario where I am only submitting the "dirty" elements from a list in a model and then mapping the model onto an EF entity.

**Comment by TylerCarlson1** [comment]
If you do that then it's not longer a collection mapping it's an update already existing items mapping, which is completely different from both AM and AM.Collection work.

You can use AM.Collection as base and copy `EquivalentExpressionAddRemoveCollectionMapper` and edit to not Remove items, then you can have your functionality.  Add to object mappers instead of the other implementation and it will get the job done.
But this wouldn't be added to AM.Collection because it breaks core functionality.

**Comment by Nils-Berghs** [comment]
I had the exact same question, from my point of view It makes perfect sence to do that, after al you are mapping to an existing list. (suppose you need to combine data from two databases, map from database one to business objects, than map from database two to the existing business units).

Anyway modifying EquivalentExpressionAddRemoveCollectionMapper seems hard to maintain. So I have created a simple work around using a list that doesn't support removing items (but lets you believe it does). See [this topic on SO](https://stackoverflow.com/questions/58394031/return-all-items-in-source-list-when-using-automapper-to-map-to-existing-list/58411407#58411407) for the full explenation.

**Comment by vratojr** [comment]
@TylerCarlson1 what about a solution like this:

we could create a class like:

```
IRemoveHandler(){
 void Remove(TDestination destination,TDestinationItem itemToRemove);
}
```
and provide the default implementation that does: ```destination.Remove(itemToRemove)```.

Then, in EquivalentExpressionAddRemoveCollectionMapper we could inject the Handler and change:

```destination.Remove(removedItem);```
to
```this.removeHandler.Remove(destination,removedItem);```

And then, when configuring the mapper, we could pass our specific implementation of the RemoveHandler.
This would not break any core behavior but still solve this problem and also that of having a soft delete like proposed in PR #21 .

What do you think?

**Comment by TylerCarlson1** [comment]
Pull Requests are always welcome.  I would just not want to break the existing API, so no remove handler defined should keep default functionality.

**Comment by cesarsouza** [comment]
+1 for adding this. It would also make it easier to implement soft-deletes, right?

**Comment by lpgoncalves** [comment]
+1 for easy soft-deletes support

**Comment by schh** [comment]
I was trying to use this today, and its a pretty common scenario that you only have added and changed object in your sourcecollection, in my case i map between two databases and send source collection through an API, i only send added or updated entities as i never delete anything in my source db, i dotn see how adding a possiblility to configure how the mapping behaves breaks the core functionality.
