### ISSUE TITLE
Support for EF 6.3 on .net core

### ISSUE THREAD

**Issue by penfold** [AutoMapper/AutoMapper.Collection#126]
We are looking to migrate to .net core 3 but use EF 6.3 instead of migrating to EF Core. (Until EF core handles a number of gaps like many-many mappings without needing intermediate pocos.)

Are there plans to support this?

Thanks,
Paul

**Comment by Tasteful** [comment]
I don't think it exists a plan but a PR with needing changes is always welcome. Probably only the TFM that need to be changed and I'm not sure how the build server will handle the new target.
