### ISSUE TITLE
How to use EqualityComparasion with Guid key ?

### ISSUE THREAD

**Issue by MelihSevsay** [AutoMapper/AutoMapper.Collection#130]
Hiii,I am struggling on Guid with EqualityComparasion.
is there any way that i use EqualityComparison with Guid or any other way to define comparison mapping between ChildEntity and Guid ?

---
I preserve ChildModel Id(s) in in ParentModel.Childs, so when i do changes, i need EqualityComparison to match Id(s) over Child Entity.
```
//Models
public class ParentModel
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public List<Guid> Childs { get; set; }
}


public class ChildModel
{
    public Guid Id { get; set; }
    public string Name { get; set; }
}

//Entity
public class ParentEntity
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public virtual List<ChildEntity> Childs { get; set; }
}


public class ChildEntity
{
    public Guid Id { get; set; }
    public string Name { get; set; }
}
```
cfg.CreateMap<Guid, ChildEntity>.EqualityComparison((model, childEntity) => model == childEntity.Id);
does not work because 'EqualityComparison' wants reference type, where Guid is not.

but if i change my model and entity Id(s) as string, it works perfect ;
cfg.CreateMap<string, ChildEntity>.EqualityComparison((model, childEntity) => model == childEntity.Id);

is there any way that i use EqualityComparison with Guid or any other way to define comparison mapping between ChildEntity and Guid ?

Thanks

**Comment by TylerCarlson1** [comment]
It should just be
`cfg.CreateMap<ChildModel,ChildEntity>.EqualityComparison((mode, entity) => model.Id == entity.Id);`
If you don't want to do that then you'll have to make a class with GUID and not Name if you don't want to map it back to do the comparison.  Or you can explicitly ignore map back name to Child.Name if it's a lookup table.

It's meant to work both ways so you just use Parent/Child Model/Entity exactly as you have them and it will handle the rest.

Also there's AutoMapper.Collection.EntityFramework that will make the Id comparison for you using the EF's primary keys.
