### ISSUE TITLE
Following does not work as expected

### ISSUE THREAD

**Issue by mnbuch** [AutoMapper/AutoMapper.Collection#134]
Class BEntity { ID, Name }
Class B { ID, Name }

```
cfg.CreateMap<BEntity, B>().ReverseMap()
                   .EqualityComparison((be, b) => be.ID == b.ID);
var source= new List<B>()
 {
     new B() { ID = 1, Name = "B Entity 1"},
     new B() { ID = 2, Name = "B Entity 2"}
};

var dest = new List<BEntity>()
{
      new BEntity() { ID = 2, Name = "B Entity 2.1"},
      new BEntity() { ID = 3, Name = "B Entity 3"}
};

var list = mapper.Map(source, dest);
```

 As far I understood `list` should have following 3 items:

{ID =1 , Name = B Entity 1}
{ID =2 , Name = B Entity 2.1}
{ID =3 , Name = B Entity3}

But this always has following 
{ID =2 , Name = B Entity 2}
{ID =1 , Name = B Entity 1}

Is my understanding incorrect?

**Comment by Tasteful** [comment]
No, the target list will only contain the items that you have in the source item. If the item already exists in the target list (as id 2) then the same object will be reused.

**Comment by mnbuch** [comment]
The following is taken from the README.MD, which is not in sync with what you are saying.

![image](https://user-images.githubusercontent.com/31439459/70022150-2b6e3f80-15b9-11ea-821b-95ecdecb9d4f.png)

**Comment by Tasteful** [comment]
It's the readme that not is correct, it think the text was meant as

- If ID's match: map OrderDTO to Order
- If OrderDTO exists and Order doesn't: add to collection
- If Order exists and OrderDTO doesn't: remove from collection

Ping @TylerCarlson1
