### ISSUE TITLE
EqualityComparison not inherited when using IncludeBase

### ISSUE THREAD

**Issue by penfold** [AutoMapper/AutoMapper.Collection#139]
I'm using IncludeBase to include a base mapping that contains the EqualityComparision expression.

The PKs exist in the base classes.

AM doesn't seem to be using this EqualityComparision expression when mapping collections of parent object mappings.

Should the mappings inherit  EqualityComparision expressions from the base mappings?

**Comment by Tasteful** [comment]
As it is built it will only use equality comparison type itself, not from the base type even that `IncludeBase` is used.

Not sure if it is possible to be notified in AM when the `IncludeBase` is invoked to setup correct equality expressions there also.
