### ISSUE TITLE
Destination Collection is removed when using CollectionMappers

### ISSUE THREAD

**Issue by scottk4016** [AutoMapper/AutoMapper.Collection#146]
I want to use AutoMapper to update collection entries where possible based on the primary key. AutoMapper.Collection seems to be the perfect solution, but I can't get it to work. Probably something very simple, but I struggling. I am expecting the test.Events to include A1, A2, A3, B4 and B5, but instead it just has A1, A2 and A3. Can someone please help?

Thanks

```csharp
using AutoMapper;
using AutoMapper.EquivalencyExpression;
using System;
using System.Collections.Generic;

namespace AutoMapperCollectionTest
{
	class Program
	{
		static void Main(string[] args)
		{
			var A1 = new A { ID = 1, Title = "TitleA1" };
			var A2 = new A { ID = 2, Title = "TitleA2" };
			var A3 = new A { ID = 3, Title = "TitleA3" };
			var B3 = new B { ID = 3, Title = "TitleB4" };
			var B4 = new B { ID = 4, Title = "TitleB4" };
			var B5 = new B { ID = 5, Title = "TitleB5" };
			var ListA = new CollectionA { ID = 100, Events = new List<A> { A1, A2, A3 } };
			var ListB = new CollectionB { ID = 100, Events = new List<B> { B3, B4, B5 } };

			var mapper = new MapperConfiguration(cfg =>
			{
				cfg.AddCollectionMappers();
				cfg.CreateMap<A, B>().EqualityComparison((s, d) => s.ID == d.ID);
				cfg.CreateMap<CollectionA, CollectionB>().EqualityComparison((s, d) => s.ID == d.ID);
			}).CreateMapper();

			var test = mapper.Map<CollectionA, CollectionB>(ListA, ListB); 
		}
	}

	public class CollectionA
	{
		public int ID { get; set; }
		public List<A> Events { get; set; }
	}

	public class CollectionB
	{
		public int ID { get; set; }
		public List<B> Events { get; set; }
	}

	public class A

	{
		public int ID { get; set; }
		public string Title { get; set; }
	}

	public class B
	{
		public int ID { get; set; }
		public string Title { get; set; }
	}
}
```

**Comment by TylerCarlson1** [comment]
This is intended functionality.
It adds A1 and A2, and maps B3 to A3, but since B4 and B5 can't find equivalents in ListA they are removed.
AutoMapper.Collections updates the original list, where as AutoMapper replaces the list with a brand new list, but in the end the items are going to have the same values.

**Comment by scottk4016** [comment]
Thanks for the clarification, Tyler. 

After posting the question I looked through the source code and found the code that removed the ones with no equivalents, so I was already thinking it was "by design".  In my real world scenario I still need AutoMapper Collections so that properties which are not set by the mapping are retained.  My need to keep entries with no equivalents is one special use case and I can actually work around it, so that's all good.  

Thanks again
Scott

**Comment by rcdailey** [comment]
I stumbled across this and have the same concern. I want to add and update items from the source to the destination dictionary, but I do not want to remove items. I think it would be great to be able to configure this library to not delete items.
