### ISSUE TITLE
Could not install on .NETFramework,Version=v4.8

### ISSUE THREAD

**Issue by prabuinet** [AutoMapper/AutoMapper.Collection#169]
Tried with install with Nuget and got this error:

Could not install package 'AutoMapper.Collection 8.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by prabuinet** [comment]
Version 7.0.1 works

**Comment by Tasteful** [comment]
AutoMapper have dropped support for .net framework. Using the old version is today the only option.
