### ISSUE TITLE
Support for AutoMapper v12

### ISSUE THREAD

**Issue by NPadrutt** [AutoMapper/AutoMapper.Collection#170]
Currently the NuGet requires a AutoMapper version >= 8 and < 12. Is there any support planned for the v12 version of AutoMapper that was released a couple of days ago?

**Comment by slubowsky** [comment]
https://github.com/AutoMapper/AutoMapper.Collection/pull/171

**Comment by marcominerva** [comment]
When will this update be published on NuGet?
