### ISSUE TITLE
Order of lists is not preserved during updates

### ISSUE THREAD

**Issue by Brunni** [AutoMapper/AutoMapper.Collection#177]
If I have a lists of Items with IDs:

e.g.
1,2,3

and the new list which should be applied to is
1,3,2

the result after applying the map is that the list still is 1,2,3

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by Brunni** [comment]
You just close all issues?

Can you shortly explain, how the mapper currently handles duplicates in the "Key"? Are there test cases for this?

What would be the expected behavior for duplicate keys? Throw exception?
