### ISSUE TITLE
Automapper and ObservableCollection

### ISSUE THREAD

**Issue by AdamJachocki** [AutoMapper/AutoMapper.Collection#183]
Hi, I have ObservableCollection. After mapping the items, Collection is being replaced by new one and does not notify about changes.

So I have my item:

```
class SomeItem
{
    public Guid Id {get; set;}
}
```

And I have container for this item:

```
class Container
{
    public ObservableCollection<SomeItem> Items { get; set; } = new();

    public Container()
    {
        Items.CollectionChanged += ItemsCollectionChanged;
    }

   private void ItemCollectionChanged(/* ... params */)
   {
  
   }
}
```

So the problem is that, when I add an item to collection, ItemCollectionChanged should be fired, because ObservableCollection will notify about the change.

But when my container is being constructed from AutoMapper, this isn't the case. My mapping is like this:

```
   CreateMap<Container, ContainerDto>().ReverseMap();
   CreateMap<SomeItem, SomeItemDto>().ReverseMap();
```

So the outcome is that, when mapping ContainerDto to Container:

- Container is being created by constructor, thus Items collection is also created and notification event is assigned
- AutoMapper assigns completely new collection to my items, when the notification event is not assigned. 

So, more less, Automapper does someting like that:

```
Container result = new Container();
ObservableCollection collection = new ObservableCollection(dtoItems);
result.Items = collection;
```

So, is just by design, that Automapper is not able to work with ObservableCollection, or is there any workaround? Or maybe this is a bug?

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
