### ISSUE TITLE
`StackOverflowException` when invoking `AddCollectionMappers()` twice.

### ISSUE THREAD

**Issue by prochnowc** [AutoMapper/AutoMapper.Collection#187]
When invoking `AddCollectionMappers()` twice all collection mapping operations throw a `StackoverflowException`.

```csharp
public class UnitTest1
{
    public class DTO { }

    public class Model { }
    
    [Fact]
    public void Test1()
    {
        var config = new MapperConfiguration(c =>
        {
            c.AddCollectionMappers();
            c.AddCollectionMappers();
            c.CreateMap<Model, DTO>();
        });

        var mapper = new Mapper(config);
        mapper.Map<ICollection<DTO>>(new List<Model>() { new Model() });
    }
}
``` 

It would be really nice if`AddCollectionMappers()` checks if the mapper is already registered. This is extremely useful when the application has many independent invocations of `services.AddAutoMapper()` in completely independent modules.

**Comment by lbargaoanu** [comment]
This project doesn't have a maintainer.

**Comment by prochnowc** [comment]
@lbargaoanu Can I open a PR to fix this problem?

**Comment by lbargaoanu** [comment]
No, there's nobody to review it.
