### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by maurosampietro** [AutoMapper/AutoMapper.Collection#22]
You use the world 'persistance' in your code and for file names but it is 'persistence' not 'persistance'

**Comment by maurosampietro** [comment]
Equivalent not 'Equivilent'
Equivalency not 'equivilency'

**Comment by Dvornik** [comment]
сomparision = сomparison

**Comment by TylerCarlson1** [comment]
Same as #7.

Now I'm hesitant to change names because the API will break.

**Comment by BrainCrumbz** [comment]
Please, do it now. And make sure to flag it as a breaking change. Before it gets *way* too late.

**Comment by Dvornik** [comment]
I totally agree with BrainCrumbz.  I have to keep my version AutoMapper.Collection with the corrected spelling to follow code guideline.

**Comment by TylerCarlson1** [comment]
@Dvornik well if you have it changed, can you send a PR to fix the spelling.  I'll review and merge and others can do as well.
