### ISSUE TITLE
Multiplicity constraint violated

### ISSUE THREAD

**Issue by maurosampietro** [AutoMapper/AutoMapper.Collection#29]
[This ](http://stackoverflow.com/questions/15885561/multiplicity-constraint-violated-the-role-of-the-relationship-has-m )error shows up while using AutomapperCollection to update from a DTO to a EF object.

Is Automapper.Collection known to work with EF at all?

**Comment by TylerCarlson1** [comment]
Yes it does.  Also the example you gave is for EF 4, so it might not be the exact same problem.

There's some issues I'm finding out with 5.x versions of AM and how mappings are made that could be causing problems. Was using 4.x for my biggest project till recently.

If you are using AM 5.x and AM.Collection 2.x then with create maps you'll have to call them twice.  Once to make an IMapper, then set GenerateEntityFrameworkPrimaryKeyEquivilentExpressions using said mapper, then make the IMapper again and then it will create equivilancy exceptions.  If you use Convention for this you don't have to double map, since the CreateMap will be called once you need it.

If you are using 4.x or changes asked above don't work, it might be something else with how you map or set up EF.  Were you able to map back to EF from DTO using AM and manually updating the lists before?

#24 will fix this, along with be compatible with upcoming 5.3 which made a mapper collection change.  The collection mapper adding and GenerateEntityFrameworkPrimaryKeyEquivilentExpressions will both be called in Initialize action for MapperConfiguration to solve this problem.

**Comment by maurosampietro** [comment]
Delving deeper into my code i found out that Automapper and `[GraphDiff](https://github.com/refactorthis/GraphDiff)` is being used simultaneously to update the DbContext.

The question is: shouldn't Automapper.Collection be sufficient to update the DbSet? 
Isn't in facts Automapper.Collection an alternative to GraphDiff?

(Hope you know GraphDiff :) )
Thank you for your time.

**Comment by maurosampietro** [comment]
Following the previous post:

Calling SaveChanges on a dbContext, after using Automapper to update the DbSet, throws an exception "Conflicting changes to the role {role} of the relationshio {relationship} have been detected"

The code is simple:

```
 Case dbCase = dbContext.Cases.Find( @case.Id );
 _mapper.Map( @case, dbCase ); 

dbContext.SaveChanges()
```

A stripped down version of the entities involved look like this:

```
public class Case
{
   public virtual ICollection<Media> Media { get; set; }
}

public class Media
{
    public virtual Case Case{get;set;}
    public virtual ICollection<Drawing> Drawings{get;set;}
}

public class Drawing
{
    public virtual Media Image { get; set; }
}


```

**Comment by maurosampietro** [comment]
I'm sorry i cannot make it work in any way

**Comment by TylerCarlson1** [comment]
Can't make your code it work or make an example to reproduce the problem?

**Comment by maurosampietro** [comment]
The situation is [this](https://github.com/AutoMapper/AutoMapper/issues/1784)

To solve that I tried this Automapper.Collection that introduced the problem described in this page. Trying to configure as you said (calling twice CreateMapper) did not help. Even without involving EF the original problem of updating an entity is not working for me. 

I think I need a minimnal complete example of a working configuration if you can provide it please.

**Comment by TylerCarlson1** [comment]
Here's a working example of your code with AM.Collections solving the update problem.
```
public class CollectionsTests
    {
        public class A
        {
            public List<B> Collection { get; set; }
        }

        public class A1
        {
            public List<B1> Collection { get; set; }
        }

        public class B
        {
            public int ID { get; set; }
            public string PropertyA { get; set; }
        }

        public class B1
        {
            public int ID { get; set; }
            public string PropertyA { get; set; }
            public string PropertyB { get; set; }
        }

        public void Collection_Map_Example()
        {
            var mapper = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<CollectionProfile>();
                cfg.CreateMap<A, A1>();
                cfg.CreateMap<B, B1>().EqualityComparision((b1, b) => b.ID == b1.ID);
            }).CreateMapper();

            var a = new A
            {
                Collection = new List<B>() {new B() {PropertyA = "c"}}
            };

            var a1 = new A1
            {
                Collection = new List<B1>() {new B1() {PropertyA = "a", PropertyB = "b"}}
            };
            mapper.Map(a, a1);
            a1.Collection.First().PropertyA.ShouldBeEquivalentTo("c");
            a1.Collection.First().PropertyB.ShouldBeEquivalentTo("b");
        }
    }
```

If you use AM.Collections.EF B1 would have ID as a key and explanation is in my first post goes over setting that up correctly.

If you are using anything other than EF 6.1.3 I don't support that and probably doesn't work.

**Comment by maurosampietro** [comment]
Thank you, at first glance it seems to work now. 
I also had to updat to EF 6.1.3.

Since all my entities have an ID I'm able to avoid EqualityComparison call by using EquivilentExpressions.GenerateEquality.Add( new GenerateEntityFrameworkPrimaryKeyEquivilentExpressions<MyContext>( _mapper ) );

Great.

The only thing I think I'm missing is to ignore B1.PropertyA so that the example should look like this:

 public void Collection_Map_Example()
        {
            var mapper = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<CollectionProfile>();
                cfg.CreateMap<A, A1>();
                cfg.CreateMap<B, B1>().ForMember( b => config.Ignore() );
            }).CreateMapper();

            var a = new A
            {
                Collection = new List<B>() {new B() {PropertyA = "c"}}
            };

            var a1 = new A1
            {
                Collection = new List<B1>() {new B1() {PropertyA = "a", PropertyB = "b"}}
            };
            mapper.Map(a, a1);
            a1.Collection.First().PropertyA.ShouldBeEquivalentTo("a"); // this fails
            a1.Collection.First().PropertyB.ShouldBeEquivalentTo("b");
        }

Can you confirm the incorrect behavior?

**Comment by maurosampietro** [comment]
After a deeper look, i found out that records are not updated, are added every time a map is performed.
I don't know exactly the context on which this happens. I'll give you more details but a question raises.. are you sure AM.Collections is designed to do a graph diff on EF?

Are there tests available?

**Comment by TylerCarlson1** [comment]
#24 adds test for EF equality comparisons.  More specificly [this](https://github.com/AutoMapper/AutoMapper.Collection/blob/b0cf119171c1c76e2378b73f520112252699c181/src/AutoMapper.Collection.EntityFramework.Tests/MapCollectionWithEqualityTests.cs). Note: The API is different than master (It solves the problem I discussed in my first comment on this thread)

Still have some other stuff to test, like Persist.  But need to create an actual DB to test it.

For your example this should get it to work.  (The issue I was talking about in first comment)
```
public void Collection_Map_Example()
        {
            var mapper = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<CollectionProfile>();
                cfg.CreateMap<A, A1>();
                cfg.CreateMap<B, B1>().ForMember( b => b.PropertyA, config => config.Ignore() );
            }).CreateMapper();

            // Set up expressions to use the first mapping to make the equivalent expressions
            EquivilentExpressions.GenerateEquality.Add( new GenerateEntityFrameworkPrimaryKeyEquivilentExpressions<MyDBContext>( _mapper ) );

             // Re-Create Mapper this time it will update the lists properly
            mapper = new MapperConfiguration(cfg =>
            {
                cfg.AddProfile<CollectionProfile>();
                cfg.CreateMap<A, A1>();
                cfg.CreateMap<B, B1>().ForMember( b => b.PropertyA, config => config.Ignore() );
            }).CreateMapper();

            var a = new A
            {
                Collection = new List<B>() {new B() {PropertyA = "c"}}
            };

            var a1 = new A1
            {
                Collection = new List<B1>() {new B1() {PropertyA = "a", PropertyB = "b"}}
            };
            mapper.Map(a, a1);
            a1.Collection.First().PropertyA.ShouldBeEquivalentTo("a"); // this fails
            a1.Collection.First().PropertyB.ShouldBeEquivalentTo("b");
        }
```

**Comment by TylerCarlson1** [comment]
Oh and you should look at #30 and #4.  Basically it's EF is picky about removing objects from child collections and will either orphan or delete them.
If you just have ID as key it will try to orphan it by setting parent's ID to null, which will throw and exception.  If you make ID and ParentID a composite primary key it will delete the object correctly.  Also #4 is a workaround if you can't do that for whatever reason.
