### ISSUE TITLE
Possible to release a strong name signed nuget-version

### ISSUE THREAD

**Issue by Tasteful** [AutoMapper/AutoMapper.Collection#3]
Is it possible to get a strong name signed nuget-version?

**Comment by TylerCarlson1** [comment]
I have to look into this.  I've heard things that some want it and some explicitly don't want it.  Also will have to learn a bit more about it first.

**Comment by Tasteful** [comment]
Know that some are against it and that others are too, many projects deliver both versions to make it work for everyone.

If you have a project that needs to be with a strong name due to the policy of the company, you can only refer others assemblies that have a strong name signing.

What many feel is a pain to use strong name is that if you have a project and need to update third-party component that uses strong name, you must either
- Build on your own project against the version
or
- Drop in the new version and add an assembly redirect the configuration of the application

Personally I think that the benefits need to actively do something when updating is to ensure the code compile and working properly instead of you just take a chance with the new version.

**Comment by TylerCarlson1** [comment]
Just so you know I plan on getting Automapper.Collections into Automapper some time in the future.  There's no reason for it not to be, just haven't gotten it in yet.  Automapper.Collections.EntityFramework will not be going in though, since it has a dependency on EntityFramework 6.

**Comment by Tasteful** [comment]
That's an better option than releasing it as a separate package.

**Comment by TylerCarlson1** [comment]
Yea it's been a PR for about a year and a half, and I use it all the time.  Easier to keep it separate entity for the time being, rather then building my own version of AutoMapper every update.

**Comment by sickboy** [comment]
@Tasteful perhaps an option? https://github.com/brutaldev/StrongNameSigner
There's others out there iirc.
