### ISSUE TITLE
Feature: Have a callback for removed items

### ISSUE THREAD

**Issue by Vaccano** [AutoMapper/AutoMapper.Collection#32]
When an item is removed from the list, it would be nice to have a callback that can allow me to deal with it.

In that call back, I could tell entity framework that the entity is "deleted".  This could even be the default action so that I can really synchronize my DTO with the entity.

But another option would be to allow me to return false, and not actually remove it from the list.  (I would probably be setting an IsActive = false in that case.

Really, I just want the first scenario for my current code.  (So I don't have to handle delete separately.)  But I can see the "IsActive" use case being useful.

Either way, this is a great project!  It has really helped me out.

**Comment by TylerCarlson1** [comment]
I would suggest looking at #4 or http://stackoverflow.com/questions/11033348/is-it-possible-to-remove-child-from-collection-and-resolve-issues-on-savechanges and http://stackoverflow.com/questions/762937/whats-the-difference-between-identifying-and-non-identifying-relationships/762994#762994 to solve this problem.

#4 is a workaround, but the SO issues explain how to fix the problem in EF if you update the keys properly.  I would recommend fixing EF.

As far as event IDK because it's not really in the scope of what AM.Collections does at its base.

**Comment by Gillardo** [comment]
I would love this!  In our code we done actually delete some objects, but mark them as deleted.  Instead of the object being removed from the collection, i would want to mark it as deleted instead.

Is this something i can do currently?

Btw, This extension is amazing!!!

**Comment by TylerCarlson1** [comment]
@Gillardo is this marked as deleted as a property of the class, or is this marked as deleted as part of the ORM?

If it's a property you could map the values and just set the deleted property in your DTO and hide deleted=true.  Unless I'm missing something

**Comment by Gillardo** [comment]
Not sure what the difference is?

But I have a deletelog class that I create when an object has been deleted. I then need to assign the ID of this deletelog variable to a property called DeleteLogId on the record that has been deleted.

Does that make sense?

Can u explain what you mean by just set the deleted property in your do and hide deleted=true???

**Comment by TylerCarlson1** [comment]
Thought maybe the delete value was in the class being mapped to, not in another class completely as your case is.

If you have EF or some other ORM that you could override SaveChanges, you could and get all items of types you want to marked to be deleted and change them to unmodified as well as add new Delete Log classes.
That's what I would do first before trying to add an event to AM.Collections to handle it.  Works for all deleted class types or just specific ones in all save cases.

**Comment by Gillardo** [comment]
I still think a callback would be good here, as surely this would help with issue #47 as upon calling the callback method, we could check if the object appears somewhere else, and if so, handle it??

**Comment by TylerCarlson1** [comment]
Make a PR then? :)

**Comment by BasharKernel** [comment]
This is very good feature I would love this too. I see that the removing is done in EquivalentExpressionAddRemoveCollectionMapper class while mapping. I think the easiest way to do this is to modify the Map method to not remove any item and make the removing on your own. I've tough of making a PR for this but I could not understand how could I register the callback for mapping and then reach it from the map function
