### ISSUE TITLE
Remove class constraint for EqualityComparision

### ISSUE THREAD

**Issue by praschl** [AutoMapper/AutoMapper.Collection#33]
I have a class like this
```
class MyClass
{
  public ICollection<DateTime> Dates{get;set}
}
```

which I want to map to this:
```
class RootEntity
{
  public ICollection<DateEntity> Dates {get;set;}
}

class DateEntity
{
  public DateTime Date {get;set;}
}
```

To do this I
```
CreateMap<DateTime, DateEntity>()
                .EqualityComparision((d, ef) => d.Date == ef.Date)
```
which wont compile, since `EqualityComparision` has its `TSource` and `TDestination` constrainted to `class`.

Can this constraint be removed without implications? Or, if not, can an alternative be created to allow for a mapping like this?

**Comment by praschl** [comment]
I have another very similar use-case with a string instead of DateTime, which works since string matches the class constraint.

**Comment by TylerCarlson1** [comment]
If you can you could use nullables and that should work.

I'll have to look into it more on that constraint, but the idea was you shouldn't be comparing structs, so things like int, double, DateTime, and complex objects in EF shouldn't be compared.

There probably isn't anything compiling wise that should be an issue, but I'll check and see

**Comment by praschl** [comment]
Unfortunately, Nullable<T>is a struct, too...

**Comment by Gillardo** [comment]
I would like to do this from an object to string as well +1

**Comment by TylerCarlson1** [comment]
object and string are both classes, theoretically you should be able to do this OOTB
