### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by mosh-hamedani** [AutoMapper/AutoMapper.Collection#34]
It'd be great if we could use this library in ASP.NET Core. I tried adding the package via .NET CLI, and even though I didn't get any compatibility issues, I couldn't find EqualityComparison() method when creating maps in a Profile.

**Comment by TylerCarlson1** [comment]
EqualityComparison is misspelled in the current version.  In 3.0 it will be fixed along with API changes for registering and supporting AM 6.x

There's a beta on AM's MyGet feed

**Comment by mosh-hamedani** [comment]
The strange thing is that when I type AutoMapper.Collection., I don't see any of the classes in the source code! I only saw one enum. What am I missing here?



On Mar 10, 2017, at 3:08 PM, Tyler Carlson <notifications@github.com<mailto:notifications@github.com>> wrote:


EqualityComparison is misspelled in the current version. In 3.0 it will be fixed along with API changes for registering and supporting AM 6.x

There's a beta on AM's MyGet feed

**Comment by TylerCarlson1** [comment]
I'm not sure I don't work with ASP.NET Core

**Comment by jbogard** [comment]
@mosh-hamedani what version of Visual Studio and .NET Core and what target framework are you on? I just tried it and it showed up just fine for me.
