### ISSUE TITLE
Info on v6 breaking changes

### ISSUE THREAD

**Issue by penfold** [AutoMapper/AutoMapper.Collection#36]
I'm looking for some details on the breaking changes for v6.

My following Collections and EF setup is somewhat broken. 

```
 private static void ConfigureAutoMapper(IUnityContainer container)
        {
            var mapperConfiguration = new MapperConfiguration(configurationExpression =>
            {
                configurationExpression.AddProfile<AutoMapper.Mappers.CollectionProfile>();  
                configurationExpression.AddProfile(new AutoMapperProfile());  
                         
            });

            IMapper mapper = mapperConfiguration.CreateMapper();
            
            EquivilentExpressions.GenerateEquality.Add(new GenerateEntityFrameworkPrimaryKeyEquivilentExpressions<ApplicationDbContext>(mapper));

            container.RegisterInstance<IMapper>(mapper);
        }
```

In particular where is `CollectionProfile` and how do I do `EquivilentExpressions.GenerateEquality.Add(new GenerateEntityFrameworkPrimaryKeyEquivilentExpressions<ApplicationDbContext>(mapper));`

Regards,
Paul

**Comment by TylerCarlson1** [comment]
It's updated in the [ReadMe](https://github.com/AutoMapper/AutoMapper.Collection) on the main page.

Will probably update the release to reflect that.

**Comment by penfold** [comment]
Sorry, didn't realise this was want I needed when I first looked. I was looking for a 'Breaking Changes' section.

This looks a lot cleaner way of setting up the mappings. Thanks.

> Can it just figure out the ID equivalency for me in EF?
> 
> Automapper.Collection.EntityFramework can do that for you.

```
Mapper.Initialize(cfg =>
        {
            cfg.AddCollectionMappers();
            cfg.SetGeneratePropertyMaps<GenerateEntityFrameworkPrimaryKeyPropertyMaps<DB>>();
			// Configuration code
        });
```
