### ISSUE TITLE
Manage Orphans in Entity Framework

### ISSUE THREAD

**Issue by TylerCarlson1** [AutoMapper/AutoMapper.Collection#4]
https://gist.github.com/TylerCarlson1/c12da95bf9cdd935b01b

Generic rudimentary implementation for finding orphans in an DataBaseContext.
Override Save changes with

```
public override int SaveChanges()
{
     new DeleteOrphans<AppsMergerContext>(this).DeleteOrphanedEntries();
     return base.SaveChanges();
}
```

Try to integrate this in with the Persist system, so user does have to handle this scenario.

**Comment by tboby** [comment]
I just ran into this case, and this seems to be a good solution. Thanks!

**Comment by TylerCarlson1** [comment]
@tboby might want to look at this?
http://stackoverflow.com/questions/11033348/is-it-possible-to-remove-child-from-collection-and-resolve-issues-on-savechanges

The first answer explains the proper way to get EntityFramework to delete the child entities without having to do any external code.
