### ISSUE TITLE
Support for KeyAttribute

### ISSUE THREAD

**Issue by cervengoc** [AutoMapper/AutoMapper.Collection#5]
Hello, just had a look at your project, and looks really promising for my needs.

Is it possible to define the collection item matching based on the existence of the `KeyAttribute` on target and source types? It would realy make things much easier, and would give a cross-ORM, nice way of controlling the logic.

**Comment by TylerCarlson1** [comment]
Yes you can make your own rules.

Just make a class with the logic inherit from `IGeneratePropertyMaps`
and make class
```
public class GetKeyExpression : GenerateEquivilentExpressionsBasedOnGeneratePropertyMaps
    {
        public GetKeyExpression()
            : base(new GetKeyProperties())
        {
        }
    }
```
Then add it to EquivilentExpressions
`EquivilentExpressions.GenerateEquality.Add(new GetKeyExpression());`

Can look at [LinqToSQL's](https://github.com/TylerCarlson1/Automapper.Collection/blob/master/src/AutoMapper.Collection/AutoMapper.Collection.LinqToSQL/GetLinqToSQLPrimaryKeyProperties.cs) implementation to get an idea of how to make your logic.
