### ISSUE TITLE
Support .NET Standard in all packages

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper.Collection#57]
Currently, AutoMapper.Collection seems to support .NET Standard, but AutoMapper.Collection.EntityFramework does not. Are there any reasons for this, or would it be possible to update the target versions of the latter package to .NET Standard?

**Comment by TylerCarlson1** [comment]
I would guess it would be the fact EF6 doesn't support .NET Standard,  EF.Core is suppose to, but they are two different systems and I don't have any implementation for EF.Core.

**Comment by jbogard** [comment]
That's exactly it.

**Comment by tlycken** [comment]
Ah, I see. If I find time for it, I might try to port the current code (or the subset of it that I need) to EF Core and file a PR.

**Comment by Tasteful** [comment]
@tlycken you have some EFCore code here https://github.com/AutoMapper/AutoMapper.Collection/tree/Tests/src/AutoMapper.Collection/AutoMapperTest.EF7 that can have correct EFCore mapping.

**Comment by tlycken** [comment]
@Tasteful Brilliant! It's primarily the inference of primary key properties I need, and that was available there. I'll see if I can get to wrapping that up in extension methods similar to those available for EF6.
