### ISSUE TITLE
EF ChangeTracker marks all entities as State.Modified after mapping

### ISSUE THREAD

**Issue by FBryant87** [AutoMapper/AutoMapper.Collection#59]
I'm trying to map a complex object to another, without creating new instances of the nested objects. (in my case, so EF's ChangeTracker won't mark them all as new entities, or modified entities unless they have changed)

When I do this:

```
                    var config = new MapperConfiguration(cfg =>
                    {
                        cfg.AddCollectionMappers();
                        cfg.CreateMap<Project, Project>().EqualityComparison((s, d) => s.ID == d.ID);
                        cfg.CreateMap<SomeNestedObject, SomeNestedObject>().EqualityComparison((s, d) => s.ID == d.ID);
                        cfg.CreateMap<SomeOtherNestedObject, SomeOtherNestedObject>().EqualityComparison((s, d) => s.ID == d.ID);
                    });

existingProject = config.CreateMapper().Map(changedProject, existingProject);
```

Every nested object within the Project is marked as modified in EF's ChangeTracker (even though I've only changed just one property in one of the nested objects). Does AutoMapper.Collection still change the object in some way, even if the properties on both source and destination are identical? (which would therefore cause EF to think something has changed)

Reference: https://stackoverflow.com/questions/45590265/automapper-confuses-changetracker

**Comment by FBryant87** [comment]
My bad! There was actually a mismatching object on one and not the other. Great tool!

**Comment by TylerCarlson1** [comment]
Ok great.  I was just trying to figure out how to explain it's probably something wrong in your configuration in EF/AutoMapper lol
