### ISSUE TITLE
.net core un loaded child collections.

### ISSUE THREAD

**Issue by adragoset** [AutoMapper/AutoMapper.Collection#61]
I guess this is more of a question than an issue but i was wondering how the collection mapper deals with unloaded entity child collections in entity framework core. I'm interested in using this to replace an injected repository dependency i use to update nested child collections on entities. Up until now i've been manually defining logic for updating unloaded nested child collections for every Domain object i create. It would be much nicer to leverage this if possible to remove this extra set of definitions i have to make to keep child collections updated regardless of if the child collection is loaded or unloaded.

**Comment by TylerCarlson1** [comment]
I'm not sure what you mean by un-loaded child collections.  I haven't played around with this in EF.Core but in EF6 the logic works by updating the child collections by either inserting/mapping/removing from said collection it will apply the proper updates back to the database.
If you have to do additional steps other than this AM.Collections probably won't work as is.

**Comment by Armog** [comment]
@adragoset did you resolve your issue with many-to-many nested collection ? 
thnx.
