### ISSUE TITLE
Upgrading AutoMapper from 6.2.0 to 6.2.1 get null reference exception on mapper initialization

### ISSUE THREAD

**Issue by slubowsky** [AutoMapper/AutoMapper.Collection#65]
Using AutoMapper and AutoMapper.Collection everything works with AutoMapper 6.2.0. After upgrading to AutoMapper 6.2.1 AutoMapper.Collection is throwing a Null Reference Exception. Originally created issue for AutoMapper as its update is what is causing the issue (https://github.com/AutoMapper/AutoMapper/issues/2415) but was requested to open it here it instead.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=AutoMapper.Collection
  StackTrace:
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c.<CreateEquivalentExpression>b__11_0(PropertyMap pm)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.CreateEquivalentExpression(IEnumerable`1 propertyMaps)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c__DisplayClass7_0.<GetEquivalentExpression>b__1(IGeneratePropertyMaps _)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c__DisplayClass7_0.<GetEquivalentExpression>b__0(TypePair tp)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationProvider configurationProvider, TypeMap typeMap)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationObjectMapper mapper, Type sourceType, Type destinationType)
   at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.IsMatch(TypePair typePair)
   at AutoMapper.MapperConfiguration.<>c__DisplayClass63_0.<FindMapper>b__0(IObjectMapper m)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at AutoMapper.MapperConfiguration.FindMapper(TypePair types)
   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
   at AutoMapper.Execution.TypeMapPlanBuilder.ResolveTypeMap(TypePair types)
   at AutoMapper.Execution.TypeMapPlanBuilder.ResolvePropertyTypeMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>b__17_1(PropertyMap pm)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(Stack`1 typeMapsPath)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(Stack`1 typeMapsPath)
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider, Stack`1 typeMapsPath)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at MyApp.API.ViewModels.Mappings.AutoMapperConfiguration.Configure(IServiceProvider provider) in C:\dev\myApp-api\MyApp.API\ViewModels\Mappings\AutoMapperConfiguration.cs:line 16
   at MyApp.API.Startup.ConfigureServices(IServiceCollection services) in C:\dev\myApp-api\MyApp.API\Startup.cs:line 218
```

**Comment by TylerCarlson1** [comment]
Like I asked in the other thread are you Running AutoMapper.Collections.EntityFramework or LinqToSQL, or some other custom auto generator of properties?  And if so could there be any maps where PK's or whatever you are mapping to aren't mapped for whatever reason?

**Comment by TylerCarlson1** [comment]
Oops sorry didn't notice you answered in other thread.  Can you give the example of that code so I can look to see if I can diagnose the problem.

I haven't supported EF.Core, or NHibernate because I don't use them and no one has requested support for them.

**Comment by slubowsky** [comment]
You mean my GenerateEntityFrameworkPrimaryKeyPropertyMaps implementation?

```
public class GenerateEntityFrameworkPrimaryKeyPropertyMaps : IGeneratePropertyMaps
{
	// TBD - figure out better way to get access to context from here. Using DI to pass params to context ctor...
	public static IServiceProvider Provider { get; set; }
	private static DbContext Context
	{
		get
		{
			return ActivatorUtilities.GetServiceOrCreateInstance<MyAppContext>(Provider);
		}
	}

	public IEnumerable<PropertyMap> GeneratePropertyMaps(TypeMap typeMap)
	{
		var propertyMaps = typeMap.GetPropertyMaps();

		var keyMembers = Context.Model.GetEntityTypes().ToList().FirstOrDefault(et => et.ClrType == typeMap.DestinationType)?.FindPrimaryKey().Properties ?? new List<IProperty>();
		var primaryKeyPropertyMatches = keyMembers.Select(m => propertyMaps.FirstOrDefault(p => p.DestinationProperty.Name == m.Name));

		return primaryKeyPropertyMatches;
	}
}
```

**Comment by TylerCarlson1** [comment]
My best guess would be to put a Try Catch in GeneratePropertyMaps.  That's what I did for the EF6 implementation, as some items wouldn't be EF related at all and would find no matches.

My guess is it's failing at `p.DestinationProperty.Name` but I don't know why it would fail now vs back then.

**Comment by slubowsky** [comment]
Nope. That's not it. Never get into catch. I don't see `GeneratePropertyMaps` in the stack trace either.

**Comment by TylerCarlson1** [comment]
Can you try `ToList()` for `primaryKeyPropertyMatches` see if that errors out.  Since it's enumerating somewhere else that might be why it isn't showing up.  I haven't gotten around to trying 6.2.1 yet with AM.Collections yet.

Also another thing can you check to see if Provider is set when generating type maps.  The order could of changed and they are getting generated before you set the Provider.

Also there's an update to the MyGet version that fixes another issue with 6.2.x which might help.

**Comment by slubowsky** [comment]
Calling `ToList` caused no exceptions.  `GeneratePropertyMaps` still appears to complete successfully for all types.

Provider is set. I'm actually manually setting that in `Mapper.Initialize` just before I call `SetGeneratePropertyMaps`.

I see a version 3.1.3 update that was just added to AutoMapper.Collections (looks like this is newest, no newer on MyGet that I could see). Installed that, it did not solve the problem.

**Comment by TylerCarlson1** [comment]
Issue might be here https://github.com/AutoMapper/AutoMapper.Collection/blob/87cda1788321e3cc5e92dbba12cae6e5a8155096/src/AutoMapper.Collection/EquivalencyExpression/EquivalentExpressions.cs#L97

The property map might be null and that's what the exception is.  There might be a change in how mapping is done where you are getting nulls in `primaryKeyPropertyMatches` and it's causing the exception.

This has been around for a while and I think before it didn't cache everything at the start and now it does it bringing this to light right away instead of delaying it to the point of using the map.

**Comment by slubowsky** [comment]
So is there anything I can do to prove the hypothesis? If correct is this a bug in AutoMapper.Collections code, or is it (also) telling me there is a problem with my mapping?

**Comment by TylerCarlson1** [comment]
@slubowsky if you could add the if statement into your code to see if it throws the exception.

Example below for line with `seeIfNullExceptionHere`

```
public class GenerateEntityFrameworkPrimaryKeyPropertyMaps : IGeneratePropertyMaps
{
	// TBD - figure out better way to get access to context from here. Using DI to pass params to context ctor...
	public static IServiceProvider Provider { get; set; }
	private static DbContext Context
	{
		get
		{
			return ActivatorUtilities.GetServiceOrCreateInstance<MyAppContext>(Provider);
		}
	}

	public IEnumerable<PropertyMap> GeneratePropertyMaps(TypeMap typeMap)
	{
		var propertyMaps = typeMap.GetPropertyMaps();

		var keyMembers = Context.Model.GetEntityTypes().ToList().FirstOrDefault(et => et.ClrType == typeMap.DestinationType)?.FindPrimaryKey().Properties ?? new List<IProperty>();
		var primaryKeyPropertyMatches = keyMembers.Select(m => propertyMaps.FirstOrDefault(p => p.DestinationProperty.Name == m.Name));

		var seeIfNullExceptionHere = !propertyMaps.Any() || propertyMaps.Any(pm => pm.DestinationProperty.GetMemberType() != pm.SourceMember.GetMemberType());
 
		return primaryKeyPropertyMatches;
	}
}
```

If it fails at setting the value I'll know for sure it's AM.Collection's code at that location.
The next question is what type map does it fail at and do you have all your PK's mapped over, is this even an intended mapping, or is it trying to map over non PK values.

I'm thinking this is a bad configuration, and the question about it is to ignore it or give a better error message explaining to the user what's going on.

**Comment by slubowsky** [comment]
So I added similar code to what you suggested and found that I do get a NullReferenceException at that point. I get this for certain mappings using both 6.2.0 and 6.2.1.
What's different is that if I comment out the offending mappings then I no longer get them in 6.2.0 (as expected) but I still do in 6.2.1!  (Perhaps because there are other parent objects that have these classes as children?)
Whats also strange is that adding a try catch doesn't catch the exception. Stack trace still doesn't show `GeneratePropertyMaps`...

The mappings that cause the problem (see below) are kind of strange, there's probably a better way to do them, but they seem to work. Using 6.2.0 my data is all being populated as I expect.

```
public class ContactInfoViewModel
{
	public int Id { get; set; }
	public string Info { get; set; }
	public int ContactInfoTypeId { get; set; }
}

public abstract class ContactInfoMapper<T>
{
	public int ContactId { get; set; }
	public T Contact { get; set; }

	public int ContactInfoId { get; set; }
	public ContactInfo ContactInfo { get; set; }
}
	
public class CompanyContactInfo : ContactInfoMapper<Company>
{
}

public class FacilityContactInfo : ContactInfoMapper<Facility>
{
}
	
etc..

The mappings:
// this one is fine
CreateMap<ContactInfoViewModel, ContactInfo>(MemberList.Source).ForMember(x => x.Id, opt => opt.Ignore());

// these cause the problem
CreateMap<ContactInfoViewModel, CompanyContactInfo>()
	.ForMember(dest => dest.ContactInfo, opt => opt.MapFrom(s => s))
	.ForAllOtherMembers(dest => dest.Ignore());
	
CreateMap<ContactInfoViewModel, FacilityContactInfo>()
	.ForMember(dest => dest.ContactInfo, opt => opt.MapFrom(s => s))
	.ForAllOtherMembers(dest => dest.Ignore());

etc..
```

**Comment by TylerCarlson1** [comment]
Yea that's a weird situation that doesn't follow the rules.  The problem is your PK's aren't being mapped over at all because your logic doesn't understand it for these weird scenarios.

ContactInfo map probably doesn't have a problem because it's a single 1 to 1 mapping under Company and Facility.  There might not be any uses of collection mapping on it.  So there's no reason to check matching PK's.  If it does check, which 6.2.1 might do anyways for whatever reason, then that will fail as well because you are ignoring the ID mapping so it gets null exception.

Simplest way to fix it is to add `.EqualityComparison((s,d) => //match condition)` to each of the mappings so they can use that for comparisons instead of trying to figure it out through property maps.

If you don't ignore ID maps they should work as well.
You can make a new IGeneratePropertyMaps that accounts for this situation to set the correct comparison and put it in front of GenerateEntityFrameworkPrimaryKeyPropertyMaps when you do your configuration.  Make sure if destination isn't 'ContactInfoMapper<T>' send back an empty list so it can go on to the next one.

**Comment by slubowsky** [comment]
I'm not really using primary keys for mapping collection data. I have kind of a weird case.

Normally we ignore Ids when mapping to entities because when updating data via a put we don't include ids in the data (they are in the URL)  - and child collections are not included either (which might be a poor implementation of put but that's how its done in our case). Without ignoring ids, it tries to update the entity ids to 0.

The usual case where we do include child collections is a create via post - when no ids or mapping to existing entities is expected.

We do implement JSON patch including support for child collections, but here, its matching on index not id (not very convenient but that's JSON patch).

So basically the id mapping is just in the way - and we always want the destination id used to prevent new entities from being created when we update entities in collections (which is the default behavior without using AutoMapper.Collections)

(We do have ids in these classes though - since the same classes are used to send data to the views, and in that direction ids are needed. Perhaps we should have a different class for each direction but we don't at the moment).

Still after reading your explanation it seems to me that when we have an id (during our patch we have ids) it doesn't hurt to map it, and for the special mappings shown earlier using `.EqualityComparison` does seem to solve the problem. So now instead of the mappings shown earlier, we have:

```
CreateMap<ContactInfoViewModel, ContactInfo>(MemberList.Source).ForMember(x => x.Id, opt => opt.Condition(src => (src.Id > 0)));
            
CreateMap<ContactInfoViewModel, CompanyContactInfo>()
                .EqualityComparison((s, d) => s.Id > 0 ? s.Id == d.ContactInfoId : false)
                .ForMember(dest => dest.ContactInfo, opt => opt.MapFrom(s => s))
                .ForAllOtherMembers(dest => dest.Ignore());
etc..
```

Ill have to test this a bit more tomorrow, but it seems to allow the initialization to complete and data appears to be mapping correctly.
Thanks!

**Comment by TylerCarlson1** [comment]
Yea that looks about right.  Think what I did once was `opt => opt.Condition(src => false)` to get around this setting ID exception issue.  It can never be mapped but the property map is there to get equality comparison and have it not fail.

The question now is what kind of error message should you get instead of NullReferenceException so you can understand what's actually going on?

**Comment by slubowsky** [comment]
Right. Also interesting that in an unrelated mapping, I had a simple missing child mapping that wasn't picked up in 6.2.0 but also caused what appeared to be the same null reference issue in 6.2.1. So obviously 6.2.1 causing a more complete look at child mappings which I guess is good - but as we've seen, hard to figure out the problem when it finds one.
