### ISSUE TITLE
Support for many to many relationships

### ISSUE THREAD

**Issue by henriquecampos** [AutoMapper/AutoMapper.Collection#67]
I'm facing a problem when i try to attach an existing entity to my object. I can update existing children properties, remove associations, and add new children, but not associate with a existing child, because if the id in the child Dto is not in the parent's collection, the child is inserted to the database with a new id.

Reference code:

    long s1;
    long p1, p2;
    
    using (var context = new ApplicationDbContext())
    {
        var suplier = context.Supliers.Add(new Suplier { Name = "Suplier1" });
        var product1 = context.Products.Add(new Product { Name = "Product1" });
        var product2 = context.Products.Add(new Product { Name = "Product2" });

        suplier.Products.Add(product2);
        context.SaveChanges();

        s1 = suplier.Id;
        p1 = product1.Id;
        p2 = product2.Id;
    }

    Console.WriteLine(String.Join(",", s1, p1, p2));

    var suplierDto = new SuplierDto
    {
        Id = s1,
        Name = "This will be updated",
        Products = new[]
        {
            new ProductDto { Id = p1, Name = "This will be inserted with new id" },
            new ProductDto { Id = p2, Name = "This will be updated" }
        }
    };

    using (var context = new ApplicationDbContext())
    {
        context.Supliers.Persist().InsertOrUpdate(suplierDto);
        context.SaveChanges();
    }

Is there any way of achieving this without having to iterate through the children and manipulating them with the Entity Context?

**Comment by TylerCarlson1** [comment]
#62 Has this same issue and I've done it once, and I've found that there's no simple easy way to account for this.
AM.Collections has no clue about EF and it's multiple relationships to a single object problems nore should it.

The scenario is so rare that I haven't seen a need to add support for this.

**Comment by henriquecampos** [comment]
I forget to mention i'm using AM.Collection.EntityFramework, with the following configuration:

    cfg.AddCollectionMappers();
    cfg.SetGeneratePropertyMaps<GenerateEntityFrameworkPrimaryKeyPropertyMaps<ApplicationDbContext>>();

    cfg.CreateMap<SuplierDto, Suplier>();
    cfg.CreateMap<ProductDto, Product>();

Also, i have the same issue in a one to many relationship if i don't have the id properties in the entity. Product.cs:

    //public long SuplierId { get; set; }  <-- if the id is omitted, the same duplicated entity issue arises
    public virtual Suplier Suplier { get; set; }

If the id is specified as non Nullable, it works as i expect, but i cant remove an existing association, because of the following exception: 

> The  operation failed: The relationship could not be changed because one or more of the foreign-key properties is non-nullable. When a change is made to a relationship, the related foreign-key property is set to a null value. If the foreign-key does not support null values, a new relationship must be defined, the foreign-key property must be assigned another non-null value, or the unrelated object must be deleted.

If the id is Nullable, then again the duplicated issue.

I don't know if all of this should work out of the box, but i'll try to find a solution to some of these problems, and then create a PR.

**Comment by TylerCarlson1** [comment]
https://stackoverflow.com/questions/11033348/is-it-possible-to-remove-child-from-collection-and-resolve-issues-on-savechanges.
You need to set the PK to include the Foreign Key to the parent.  Then when you remove from list it will remove from database.  If you don't have it as part of the key it will try to orphan it by setting the ID to null and giving you the exception if it's non null-able.

**Comment by fabianus76** [comment]
> The scenario is so rare that I haven't seen a need to add support for this.

Hi TylerCarlson1, I found this thread and your statement and would like to say, that this scenario isn't rare in my opinion. It isn't that often as one to many, but it is a fundamental relation!

I tried to solve it with this, but it still will create new instances of "Person" when I try to relate an existing Person to an existing Union by creating a PersonXUnion. I am astonished that it does even with the following mapping. 

Here are my models (which serve as DTOs, too): 

```
public class Union
   {
       public int Id { get; set; }
       public List<PersonXUnion> PersonXUnionList { get; set; } = new List<PersonXUnion>();
}


   public class PersonXUnion
   {

       public int Id { get; set; }
       public int PersonId { get; set; }
       public Person Person { get; set; }

       public int UnionId { get; set; }
       public Union Union { get; set; }

   }


   public class Person
   {
       public int Id { get; set; }
       public List<PersonXUnion> PersonXUnionList { get; set; } = new List<PersonXUnion>();
   }
```


here is my automapper  mapping: 


```
var config = new MapperConfiguration(cfg =>
                {
                  cfg.AddCollectionMappers();
                  cfg.CreateMap<Union, Union>()
                        .EqualityComparison((odto, o) => odto.Id == o.Id)
                        .ForMember(d => d.PersonXUnionList, o => o.MapFrom(s => s.PersonXUnionList))
					;
					
		cfg.CreateMap<PersonXUnion, PersonXUnion>()
                        .EqualityComparison((odto, o) => odto.Id == o.Id)

                        .ForMember(dest => dest.Person,
                                m => m.MapFrom(clientJsonObj => 
                            _context.Person.FirstOrDefault(
                                contextDb => contextDb.Id == clientJsonObj.Person.Id)))
								
						.ForMember(d => d.Union, o => o.MapFrom(s => s.Union))
                    ;
					
		cfg.CreateMap<Person, Person>()
                        .EqualityComparison((odto, o) => odto.Id == o.Id)
					;
}
```

**Comment by TylerCarlson1** [comment]
Your scenario is a many to many relationship using an in-between table.  That's different then using a many to many relationship in Entity Framework, which is much much harder to support.

To solve get it to work you need to make DTO objects and not clone.  You shouldn't be doing this anyways, but the problem here is in your linking table you are copying over the person and union object which is cloning the data.

You need your PersonXUnionDTO to not include Person or Union so that when mapping back to EF it will make use of the ID and not the item itself.  The issue you have right now is because you are using _context it's most likely a new instance of DBContext from the one you are saving, so EF doesn't realize it's an existing item, because it's tied to the other Context when you retrieved it.

This only works if you are saving existing entities where the id is already known.  If creating a new item and associating at the same time it isn't going to know, so if you need both cases you are going to have to do a pre-condition to not map the Person or Union if ID already exists for that relationship.  If you are editing both the Person and the Union at the same time in the same save, then that's impossible with just simple AutoMapper.  You'll need to get the context used to do the proper mappings, or pre-save so that you can just use the IDs.

It gets incredibly complicated, if you want full support in all cases for your mapping.

**Comment by fabianus76** [comment]
Hi TylerCarlson1, thanks a lot for your kind and detailed help. I almost solved the problem thanks to your advice. There is one last thing that remains, but let me first state where I am right now

Here is the basic structure: 


   ```
public class Union
   {
	public int Id { get; set; }
       public List<PersonXUnion> PersonXUnionList { get; set; } = new List<PersonXUnion>();
}

   public class UnionDto:   {
public int Id { get; set; }
       public List<PersonXUnionDto> PersonXUnionList { get; set; }
   }



   public class PersonXUnion
   {
	public int Id { get; set; }
       public int PersonId { get; set; }
       public virtual Person Person { get; set; }

       public int UnionId { get; set; }
       public Union Union { get; set; }

   }

   public class PersonXUnionDto
   {
	public int Id { get; set; }
       public PersonDto Person { get; set; }
       // you must not use this property otherwise automapper won't work !!!:
       // public UnionDto Union { get; set; }
   }


   public class Person
   {
       public int Id { get; set; }
       public string FirstName { get; set; }
       public string LastName { get; set; }
       public List<PersonXUnion> PersonXUnionList { get; set; } = new List<PersonXUnion>();
   }

   public class PersonDto 
   {
	public int Id { get; set; }
       public string FirstName { get; set; }
       public string LastName { get; set; }
   }
```



And here is the part of the automapper configuration: 



```
var config = new MapperConfiguration(cfg =>
               {
                   // cfg.AllowNullCollections = true;
                   cfg.AddCollectionMappers();


                   cfg.CreateMap<PersonDto, Person>()
                        .EqualityComparison((odto, o) => odto.Id == o.Id)
                        .ForMember(d => d.FirstName, o => o.MapFrom(s => s.FirstName))
                        .ForMember(d => d.LastName, o => o.MapFrom(s => s.LastName))
                        .ForAllOtherMembers(opts => opts.Ignore())
                    ;
                  
cfg.CreateMap<UnionDto, Union>()
                       .EqualityComparison((odto, o) => odto.Id == o.Id)
                       .ForMember(d => d.PersonXUnionList, o => o.MapFrom(s => s.PersonXUnionList))
                   .ForAllOtherMembers(opts => opts.Ignore())
                   ;


cfg.CreateMap<PersonXUnionDto, PersonXUnion>()
                       .EqualityComparison((odto, o) => odto.Id == o.Id)
                       .ForMember(d => d.Person, o => o.MapFrom(s => s.Person))
                           .ForMember(dest => dest.Person,
                               m => m.MapFrom(clientJsonObj =>
                               _context.Person.FirstOrDefault(
                                   contextDb => contextDb.Id == clientJsonObj.Person.Id)))
                   .ForAllOtherMembers(opts => opts.Ignore())
                   ;
```

Now I am able to add an existing Person to a Union (adding a PersonXUnion) and automapper does the job without presave. 

BUT, If I modify for example the firstName of a Person in an existing PersonXUnion, this change is not mapped. If I replace this: 

```
cfg.CreateMap<PersonXUnionDto, PersonXUnion>()
                       .EqualityComparison((odto, o) => odto.Id == o.Id)
                       .ForMember(d => d.Person, o => o.MapFrom(s => s.Person))
                           .ForMember(dest => dest.Person,
                               m => m.MapFrom(clientJsonObj =>
                               _context.Person.FirstOrDefault(
                                   contextDb => contextDb.Id == clientJsonObj.Person.Id)))
                   .ForAllOtherMembers(opts => opts.Ignore())
```


with this: 


```
cfg.CreateMap<PersonXUnionDto, PersonXUnion>()
                       .EqualityComparison((odto, o) => odto.Id == o.Id)
                       .ForMember(d => d.Person, o => o.MapFrom(s => s.Person))
                           .ForMember(d => d.Person, o => o.MapFrom(s => s.Person))
                   .ForAllOtherMembers(opts => opts.Ignore())
```


The modification of FirstName IS mapped. BUT, when I us this last config in the case where I add an existing Person to a Union (by adding a new PersonXUnion), I get the following error 

"Error mapping types.\r\n\r\nMapping types:\r\nUnionDto -> Union\r\nHost.API.Dtos.UnionDto -> Host.API.Models.Union\r\n\r\nType Map configuration:\r\nUnionDto -> Union\r\nHost.API.Dtos.UnionDto -> Host.API.Models.Union\r\n\r\nDestination Member:\r\nPersonXUnionList\r\n"

I would love to have one config that works for both - adding and modification. 
Would be wonderful if you could have look one more time. 

Thank you!

**Comment by TylerCarlson1** [comment]
From what I see there I'm guessing you have a single context object, otherwise the add wouldn't work.
That's not good practices to keep the context open all the time, but in this case simplifies thing.

In that case what you do is in `cfg.CreateMap<PersonXUnionDto, PersonXUnion>()` keep the first one but do an after map where you map PersonDto to Person explicitly, or use ResolveValue to get it from the database, and it will map over afterwards.  That way adding existing person works, but then you explicitly map the changes after, so it will show up in your save.
Issue is when you map you are just getting the item from the database, but to map it you will have to explicitly call it yourself in an after map and that should fix the issue for your particular situation.

**Comment by redradist** [comment]
Is there any updates according Many-to-Many ?

Seems like this one my issue https://github.com/AutoMapper/AutoMapper.Collection.EFCore/issues/43#issuecomment-692025474 happens exactly do not missed support for Many-to-Many relation ...
