### ISSUE TITLE
When upgrading from 6.1.1 to 6.2.1 there appears to be an issue with null properties which are now being mapped resulting in exceptions.

### ISSUE THREAD

**Issue by maevans1** [AutoMapper/AutoMapper.Collection#68]
Mapping one object to another using same  class to another where a property Statuses was defined but the value was null now results in an exception as it appear automapper is now mapping null values.

"System.Web.Mvc.SelectList needs to have a constructor with 0 args or only optional args. Parameter name: type"

**Mapping Definition**
       cfg.CreateMap<Areas.LOA.Models.NonSalesEventBaseSearchView, Areas.LOA.Models.NonSalesEventBaseSearchView>()
                    .ForMember(x => x.Prop1 , opt => opt.Ignore())
                    .ForMember(x => x.Prop2, opt => opt.Ignore())
                    .ForMember(x => x.Prop3, opt => opt.Ignore());         

**Mapping Line..** 
   AutoMapper.Mapper.Map<NonSalesEventBaseSearchView,NonSalesEventBaseSearchView>(previousSearchCriteria, viewModel);

**Class** 
NonSalesEventBaseSearchView

 public SelectList Statuses { get; set; }

**Comment by TylerCarlson1** [comment]
Sounds more like an issue for AutoMapper.  There's been a new release 6.2.2 which fixes bugs with mapping lists.  That might fix the problem.
