### ISSUE TITLE
Fixing Typos?

### ISSUE THREAD

**Issue by mrmashal** [AutoMapper/AutoMapper.Collection#7]
I really really like your extension for Automapper. But I just noticed a few word-spelling errors:

Equivilency -> Equivalency
Equivilent, Equivlent -> Equivalent
Comparision -> Comparison
Persistance -> Persistence
GeneratEquivilentExpression -> GenerateEquivalentExpression

Is it possible to fix them?

**Comment by TylerCarlson1** [comment]
Ooops.  I wouldn't mind fixing them, but then that means the API might break if there's changes there.  I'll have to go over what's miss-spelled and see how it will effect things.

**Comment by mrmashal** [comment]
Yep, I see. It's no biggie. You can close this whenever you want.

Thanks again for the great stuff. It saved me a lot of time :)

**Comment by BrainCrumbz** [comment]
Same here: Please, do it now. And make sure to flag it as a breaking change. Before it gets *way* too late.
