### ISSUE TITLE
Change unit test framwork

### ISSUE THREAD

**Issue by Tasteful** [AutoMapper/AutoMapper.Collection#74]
The Fixie test framework is simple and probly flexible, if you learn how to configure it correctly. 

Example test inherited from a base class will not be found correctly and the test names is visible on the base class and not on the derived types, this make it harder to use the same test cases with different configurations.

The test framework does not either work with new features in Visual Studio like live unit testing.

Can the test framework be changed to [xUnit](https://xunit.github.io/) that have more capabilities and activly developed?

**Comment by rizi** [comment]
@Tasteful how do I run the unit tests with Fixie within Visual Studio? br

**Comment by TylerCarlson1** [comment]
I guess so since AM was changed back to xUnit as well.  Pull Request?  So can guarantee that it works with all new VS features.

**Comment by Tasteful** [comment]
I will create a PR.
