### ISSUE TITLE
Collection clear with equalitycomparision

### ISSUE THREAD

**Issue by ste4net** [AutoMapper/AutoMapper.Collection#79]
### Source/destination types

```csharp
    public class GroupPerUser
    {
        public long UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
        public long GroupId { get; set; }
        public VehicleGroup Group { get; set; }
    }
    public class UserProfile : IdentityUser<long>, IDomainEntity
    {
        public virtual List<GroupPerUser> EnabledGroups { get; set; }
    }

    public class UserProfileVMTest : UserProfile
    {

    }
```

### Mapping configuration

```csharp
services.AddAutoMapper(c => { c.AddCollectionMappers(); c.AddProfile<MyMapperProfile>(); });
[...]
 CreateMap<GroupPerUser, GroupPerUser>()
                .EqualityComparison((g1, g2) => g1.UserProfileId == g2.UserProfileId && g1.GroupId == g2.GroupId);
```

### Expected behavior
From my understanding using AddCollectionMappers collections have to be updated depending on equality comparision.

### Actual behavior
In this case i see that collection is first cleared then filled. This produce an issue with EF changeTracker.
### Steps to reproduce

```csharp
      protected IMapper Mapper
        {
            get
            {
                if (_mapper == null)
                    _mapper = _serviceProvider.GetService<IMapper>();
                return _mapper;
            }
        }
[...]
var debugPlan = Mapper.ConfigurationProvider.BuildExecutionPlan(typeof(UserProfileVMTest), typeof(UserProfile));
Mapper.Map<UserProfileVMTest, UserProfile>(Model, Entity);
            
```

**Comment by TylerCarlson1** [comment]
It should as long as your CreateMap is called in the MyMapperProfile.  I honestly haven't tried the BuildExecutionPlan to see if it's in sync or not.  Also I'm not 100% sure when you map a class to itself it will mess up the equality logic or not.  AutoMapper doesn't allow that by default and it's more of a hack in this instance.

Another thing could be that `services.AddAutoMapper` could have an issue with registering it.  I'm not super familiar with how that works.

**Comment by TylerCarlson1** [comment]
Oh I might know what the issue might be. You have to set EnabledGroups to a value on constructor or parameter initialization.

```
public class UserProfile : IdentityUser<long>, IDomainEntity
    {
        public virtual List<GroupPerUser> EnabledGroups { get; set; } = new HashSet<GroupPerUser>();
    }
```
This should fix the updating problems in Entity Framework

**Comment by ste4net** [comment]
Thank you very much. 
I use often this approach when i have simple entity avoiding to create child DTO.
But... sorry it was not an Autmapper issue i have been messed up by the fact that it was happening only using mapping function but going a little bit deeper i saw that it was not Automapper deleting items it was EfCore calling dbCtx.Entry(tmpEnt)
It was a stupid things related to USerProfile property of GroupPerUser. 
Source was null and obviously Automapper set null to destination than EFCore seeing that the property has been changed to null treat it like a removed entity and remove it from collection .
Simply solved asking Automapper to ignore that property 
``
CreateMap<GroupPerUser, GroupPerUser>()
                .EqualityComparison((g1, g2) => g1.UserProfileId == g2.UserProfileId && g1.GroupId == g2.GroupId).ForMember(g => g.UserProfile, m => m.Ignore());
``

Thank you for your help.

**Comment by TylerCarlson1** [comment]
For your DTO's it's recommended not to have circular references, because it causes things like that.  Also causes issues with projection and setting a max depth to stop the circular reference.

Best would be to make a new GroupPerUserVM and not include UserProfile property and that should cause the least amount of problems going forward.

**Comment by ste4net** [comment]
Sure, thank you . I usually avoid circular references excluding property from Json serialization.
